version: '3.1'

services:
  mongo:
    image: mongo
    restart: "no"
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: miguelon

  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: miguelon
      ME_CONFIG_MONGODB_URL: mongodb://root:miguelon@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"